### ISSUE TITLE
[BUG - found cause] zero ada error mistakenly raised

### ISSUE THREAD

**Issue by KristianBalaj** [mlabs-haskell/plutus-simple-model#16] opened 2022-05-05 16:59 UTC
I've posted #15 issue some time ago and when I was digging deeper into the actual problem I've found out that there is probably a bug somewhere and created the minimal reproducible example.

The following code fails the test with the zero ada error even when there should be no such error.

I found out that this happens when I changed this package in the project from commit `64f37881c3c6a1ece104413e95b6a272d22dbfaa` to `2077162655a62f9b6404e153eed3ef56c65cad67`

**EDIT:**
The error occurs with both of the commits, so the bug is implemented somewhere further in the past.
Modifying this line: 

```haskell
void $ sendValue admin (Ada.toValue minAdaTxOut <> Value.assetClassValue (fakeCoin (FakeCoin "SMTH")) 10_000_000) user
``` 

to this:

```haskell
void $ sendValue admin (Ada.toValue minAdaTxOut <> Ada.toValue minAdaTxOut  <> Value.assetClassValue (fakeCoin (FakeCoin "SMTH")) 10_000_000) user
```
solves the error.

However, it should work either way in my opinion.

<details>
<summary>Buggy code</summary>

```haskell
{-# LANGUAGE NumericUnderscores #-}
{-# LANGUAGE OverloadedStrings #-}

module Spec.MyTest where

import Control.Monad
import Ledger
import qualified Ledger.Value as Value
import Plutus.Test.Model
import qualified Plutus.V1.Ledger.Ada as Ada
import Test.Tasty
import Utils.Helpers (checkBool)

main :: IO ()
main = do
  cfg <- readDefaultBchConfig
  defaultMain $
    testGroup
      "benchmark test suite"
      [ tests cfg
      ]

tests :: BchConfig -> TestTree
tests cfg =
  testGroup
    "Foo"
    [ check True "foo" foo'
    ]
  where
    tokens = Value.assetClassValue (fakeCoin (FakeCoin "SMTH")) 10_000_000

    check :: Bool -> String -> Run Bool -> TestTree
    check = checkBool cfg (Ada.adaValueOf 100_000_000 <> tokens)

    foo' = do
      user <- newUser mempty
      admin <- getMainUser
      void $ sendValue admin (Ada.toValue minAdaTxOut <> Value.assetClassValue (fakeCoin (FakeCoin "SMTH")) 10_000_000) user
      foo user

foo :: PubKeyHash -> Run Bool
foo user = do
  admin <- getMainUser
  let spendVal = Ada.toValue minAdaTxOut
  sp <- sendValue admin spendVal user >> spend user spendVal
  void $ Plutus.Test.Model.signTx user (userSpend sp <> payToPubKey admin spendVal) >>= sendTx
  noErrors
```

</details>

**Comment by KristianBalaj** [comment] 2022-05-17 13:15
I've come across this issue once again and I've found the cause.

When I look at the user's UTXOs (`utxoAt <$> getMainUser`) I can find these fractured UTXOs there.

```haskell

[ ( TxOutRef
        { txOutRefId = 157 a6dc880c001b691c6be2bc02f5d1b9dbfca6244a2fc2292a631cf38f560ac,
          txOutRefIdx = 3
        },
      TxOut
        { txOutAddress = Address {addressCredential = PubKeyCredential 918 f37f350507ca60236ef12a001f7405198df34d68e48178b75d98a, addressStakingCredential = Nothing},
          txOutValue = Value (Map [(,Map [("", 2000000)]), (3 d88123b74593927b403fb99108a5b7594fc03ad8677d95172df8778, Map [("asset", 1000000000)])]),
          txOutDatumHash = Nothing
        }
    ),
    ( TxOutRef
        { txOutRefId = 157 a6dc880c001b691c6be2bc02f5d1b9dbfca6244a2fc2292a631cf38f560ac,
          txOutRefIdx = 4
        },
      TxOut
        { txOutAddress = Address {addressCredential = PubKeyCredential 918 f37f350507ca60236ef12a001f7405198df34d68e48178b75d98a, addressStakingCredential = Nothing},
          txOutValue = Value (Map [(,Map [("", 29999988000000)]), (3 d88123b74593927b403fb99108a5b7594fc03ad8677d95172df8778, Map [("asset", 198000000000)])]),
          txOutDatumHash = Nothing
        }
    )
  ]

```

The problem is that when I want to send a transaction that does `userSpend` with minAda, the first user's UTXO gets consumed and it results in `Transaction outputs should not contain zero Ada` because there is still the asset in the UTXO that remains without the spent Ada there.

I don't think this is right behaviour since the user has enough Ada still at his address. Correct me if I'm wrong 🙌

**Comment by anton-k** [comment] 2022-07-05 11:34
I guess it can be caused by plutus bug in `lt` it caused wrong implementation for `spend`.
It was recently fixed in the code by iusing correct `lt` implementation

**Closed** 2022-08-03 17:27 UTC
